export const ADD_FETCHED_PRODUCT = 'ADD_FETCHED_PRODUCT';
export const APPEND_POSTED_PRODUCT = 'APPEND_POSTED_PRODUCT';
export const TOGGLE_PRODUCT_LOADER = 'TOGGLE_PRODUCT_LOADER';
export const APPEND_POSTED_PRODUCT_SUCCESS = 'APPEND_POSTED_PRODUCT_SUCCESS';
export const APPEND_POSTED_PRODUCT_ERROR = 'APPEND_POSTED_PRODUCT_ERROR';
